### ISSUE TITLE
Add hid value so that canonical meta value can be overriden

### ISSUE THREAD

**Issue by BrianGilbert** [druxt/druxt-router#70]
**Describe the bug**
The canonical meta tag declared by druxt-router is missing hid value that allows you to override it.

As per https://nuxtjs.org/docs/2.x/features/meta-tags-seo/

_To avoid any duplication when used in child components, please give a unique identifier with the `hid` key to the meta description. This way `vue-meta` will know that it has to overwrite the default tag._

**To Reproduce**
1. add the following to a pages default export
```
  head() {
    return {
      link: [
        {
          hid: 'canonical',
          rel: 'canonical',
          href: 'https://www.test.com/path',
        },
      ],
    }
  },
```
2. You will receive 2 canonical meta tags

**Expected behavior**
Should only receive the canonical tag from your export.

**Comment by Decipher** [comment]
Fixed and committed. Thanks @BrianGilbert
